http:
  port: ${GATEWAY_PORT}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  transaction_queuer:
    host: 'localhost'
    paths: '/client/:clientId/transactions'
    methods: ["POST"]
  fail_reader:
    host: 'localhost'
    paths: 
      - '/playables/fails'
      - '/transactions/fails'
    methods: ["GET", "OPTIONS"]
  transaction_cache_reader:
    host: 'localhost'
    paths: '/client/:clientId/transactions'
    methods: ["GET", "OPTIONS"]
  playable_cache_reader:
    host: 'localhost'
    paths: '/client/:clientId/playables'
    methods: ["GET", "OPTIONS"]
serviceEndpoints:
  transaction_queuer:
    url: 'http://${SERVICE_TRANSACTION_QUEUER_HOST}:${SERVICE_TRANSACTION_QUEUER_PORT}'
  transaction_cache_reader:
    url: 'http://${SERVICE_TRANSACTION_CACHE_READER_HOST}:${SERVICE_TRANSACTION_CACHE_READER_PORT}'
  playable_cache_reader:
    url: 'http://${SERVICE_PLAYABLE_CACHE_READER_HOST}:${SERVICE_PLAYABLE_CACHE_READER_PORT}'
  fail_reader:
    url: 'http://${SERVICE_FAIL_READER_HOST}:${SERVICE_FAIL_READER_PORT}'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: transaction_queuer
    apiEndpoints:
      - transaction_queuer
    policies:
      - proxy:
          - action:
              serviceEndpoint: transaction_queuer
  - name: transaction_cache_reader
    apiEndpoints:
      - transaction_cache_reader
    policies:
      - proxy:
          - action:
              serviceEndpoint: transaction_cache_reader
  - name: playable_cache_reader
    apiEndpoints:
      - playable_cache_reader
    policies:
      - proxy:
          - action:
              serviceEndpoint: playable_cache_reader
  - name: fail_reader
    apiEndpoints:
      - fail_reader
    policies:
      - proxy:
          - action:
              serviceEndpoint: fail_reader
